// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alarm/alarm.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	alarm/alarm.proto

It has these top-level messages:
	CreateRequest
	CreateReply
	AddRequest
	AddReply
	EndRequest
	EndReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	FlowID   uint32 `protobuf:"varint,2,opt,name=FlowID" json:"FlowID,omitempty"`
	Source   string `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=Type" json:"Type,omitempty"`
	Strategy string `protobuf:"bytes,5,opt,name=Strategy" json:"Strategy,omitempty"`
	Target   string `protobuf:"bytes,6,opt,name=Target" json:"Target,omitempty"`
	SourceID string `protobuf:"bytes,7,opt,name=SourceID" json:"SourceID,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateRequest) GetFlowID() uint32 {
	if m != nil {
		return m.FlowID
	}
	return 0
}

func (m *CreateRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CreateRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *CreateRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *CreateRequest) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

type CreateRequestTime struct {
}

func (m *CreateRequestTime) Reset()                    { *m = CreateRequestTime{} }
func (m *CreateRequestTime) String() string            { return proto.CompactTextString(m) }
func (*CreateRequestTime) ProtoMessage()               {}
func (*CreateRequestTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type CreateRequest_Location struct {
	Lng float32 `protobuf:"fixed32,1,opt,name=lng" json:"lng,omitempty"`
	Lat float32 `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
}

func (m *CreateRequest_Location) Reset()                    { *m = CreateRequest_Location{} }
func (m *CreateRequest_Location) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest_Location) ProtoMessage()               {}
func (*CreateRequest_Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *CreateRequest_Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreateRequest_Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type CreateRequest_Data struct {
}

func (m *CreateRequest_Data) Reset()                    { *m = CreateRequest_Data{} }
func (m *CreateRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest_Data) ProtoMessage()               {}
func (*CreateRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type CreateReply struct {
	V   string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CreateReply) Reset()                    { *m = CreateReply{} }
func (m *CreateReply) String() string            { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()               {}
func (*CreateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateReply) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *CreateReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddRequest struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	FlowID   uint32 `protobuf:"varint,2,opt,name=FlowID" json:"FlowID,omitempty"`
	Source   string `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=Type" json:"Type,omitempty"`
	Strategy string `protobuf:"bytes,5,opt,name=Strategy" json:"Strategy,omitempty"`
	Target   string `protobuf:"bytes,6,opt,name=Target" json:"Target,omitempty"`
	SourceID string `protobuf:"bytes,7,opt,name=SourceID" json:"SourceID,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AddRequest) GetFlowID() uint32 {
	if m != nil {
		return m.FlowID
	}
	return 0
}

func (m *AddRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *AddRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *AddRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AddRequest) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

type AddRequestTime struct {
}

func (m *AddRequestTime) Reset()                    { *m = AddRequestTime{} }
func (m *AddRequestTime) String() string            { return proto.CompactTextString(m) }
func (*AddRequestTime) ProtoMessage()               {}
func (*AddRequestTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type AddRequest_Location struct {
	Lng float32 `protobuf:"fixed32,1,opt,name=lng" json:"lng,omitempty"`
	Lat float32 `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
}

func (m *AddRequest_Location) Reset()                    { *m = AddRequest_Location{} }
func (m *AddRequest_Location) String() string            { return proto.CompactTextString(m) }
func (*AddRequest_Location) ProtoMessage()               {}
func (*AddRequest_Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *AddRequest_Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *AddRequest_Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type AddRequest_Data struct {
}

func (m *AddRequest_Data) Reset()                    { *m = AddRequest_Data{} }
func (m *AddRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*AddRequest_Data) ProtoMessage()               {}
func (*AddRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

type AddReply struct {
	V   string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *AddReply) Reset()                    { *m = AddReply{} }
func (m *AddReply) String() string            { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()               {}
func (*AddReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddReply) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *AddReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type EndRequest struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	FlowID   uint32 `protobuf:"varint,2,opt,name=FlowID" json:"FlowID,omitempty"`
	Source   string `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=Type" json:"Type,omitempty"`
	Strategy string `protobuf:"bytes,5,opt,name=Strategy" json:"Strategy,omitempty"`
	Target   string `protobuf:"bytes,6,opt,name=Target" json:"Target,omitempty"`
	SourceID string `protobuf:"bytes,7,opt,name=SourceID" json:"SourceID,omitempty"`
}

func (m *EndRequest) Reset()                    { *m = EndRequest{} }
func (m *EndRequest) String() string            { return proto.CompactTextString(m) }
func (*EndRequest) ProtoMessage()               {}
func (*EndRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EndRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EndRequest) GetFlowID() uint32 {
	if m != nil {
		return m.FlowID
	}
	return 0
}

func (m *EndRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EndRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EndRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *EndRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *EndRequest) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

type EndRequestTime struct {
}

func (m *EndRequestTime) Reset()                    { *m = EndRequestTime{} }
func (m *EndRequestTime) String() string            { return proto.CompactTextString(m) }
func (*EndRequestTime) ProtoMessage()               {}
func (*EndRequestTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type EndRequest_Location struct {
	Lng float32 `protobuf:"fixed32,1,opt,name=lng" json:"lng,omitempty"`
	Lat float32 `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
}

func (m *EndRequest_Location) Reset()                    { *m = EndRequest_Location{} }
func (m *EndRequest_Location) String() string            { return proto.CompactTextString(m) }
func (*EndRequest_Location) ProtoMessage()               {}
func (*EndRequest_Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *EndRequest_Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *EndRequest_Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type EndRequest_Data struct {
}

func (m *EndRequest_Data) Reset()                    { *m = EndRequest_Data{} }
func (m *EndRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*EndRequest_Data) ProtoMessage()               {}
func (*EndRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 2} }

type EndReply struct {
	V   string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *EndReply) Reset()                    { *m = EndReply{} }
func (m *EndReply) String() string            { return proto.CompactTextString(m) }
func (*EndReply) ProtoMessage()               {}
func (*EndReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EndReply) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *EndReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pb.createRequest")
	proto.RegisterType((*CreateRequestTime)(nil), "pb.createRequest.time")
	proto.RegisterType((*CreateRequest_Location)(nil), "pb.createRequest.Location")
	proto.RegisterType((*CreateRequest_Data)(nil), "pb.createRequest.Data")
	proto.RegisterType((*CreateReply)(nil), "pb.createReply")
	proto.RegisterType((*AddRequest)(nil), "pb.addRequest")
	proto.RegisterType((*AddRequestTime)(nil), "pb.addRequest.time")
	proto.RegisterType((*AddRequest_Location)(nil), "pb.addRequest.Location")
	proto.RegisterType((*AddRequest_Data)(nil), "pb.addRequest.Data")
	proto.RegisterType((*AddReply)(nil), "pb.addReply")
	proto.RegisterType((*EndRequest)(nil), "pb.endRequest")
	proto.RegisterType((*EndRequestTime)(nil), "pb.endRequest.time")
	proto.RegisterType((*EndRequest_Location)(nil), "pb.endRequest.Location")
	proto.RegisterType((*EndRequest_Data)(nil), "pb.endRequest.Data")
	proto.RegisterType((*EndReply)(nil), "pb.endReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Add service

type AddClient interface {
	// create 更新报警记录
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*EndReply, error)
}

type addClient struct {
	cc *grpc.ClientConn
}

func NewAddClient(cc *grpc.ClientConn) AddClient {
	return &addClient{cc}
}

func (c *addClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := grpc.Invoke(ctx, "/pb.Add/create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := grpc.Invoke(ctx, "/pb.Add/add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addClient) End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*EndReply, error) {
	out := new(EndReply)
	err := grpc.Invoke(ctx, "/pb.Add/end", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Add service

type AddServer interface {
	// create 更新报警记录
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Add(context.Context, *AddRequest) (*AddReply, error)
	End(context.Context, *EndRequest) (*EndReply, error)
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Add_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Add_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).End(ctx, req.(*EndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Add",
	HandlerType: (*AddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Add_Create_Handler,
		},
		{
			MethodName: "add",
			Handler:    _Add_Add_Handler,
		},
		{
			MethodName: "end",
			Handler:    _Add_End_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarm/alarm.proto",
}

func init() { proto.RegisterFile("alarm/alarm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x53, 0x41, 0x6b, 0xf2, 0x40,
	0x10, 0x75, 0x13, 0xbf, 0x7c, 0x3a, 0x55, 0x5b, 0xf7, 0x50, 0x96, 0xd0, 0x83, 0x04, 0x0a, 0x52,
	0x68, 0x84, 0xf6, 0x17, 0x14, 0x42, 0x21, 0xd0, 0x53, 0xf4, 0x0f, 0x8c, 0x66, 0x09, 0x42, 0xcc,
	0x6e, 0xd7, 0xd5, 0x92, 0x73, 0xff, 0x70, 0xa1, 0x7f, 0xa0, 0xec, 0x24, 0x6a, 0x7b, 0xf3, 0xee,
	0x25, 0xcc, 0x7b, 0x79, 0x6f, 0x98, 0x37, 0xbb, 0x0b, 0x63, 0x2c, 0xd1, 0x6c, 0x66, 0xf4, 0x8d,
	0xb5, 0x51, 0x56, 0x71, 0x4f, 0x2f, 0xc3, 0xbb, 0x42, 0xa9, 0xa2, 0x94, 0x33, 0xd4, 0xeb, 0x19,
	0x56, 0x95, 0xb2, 0x68, 0xd7, 0xaa, 0xda, 0x36, 0x8a, 0xe8, 0x9b, 0xc1, 0x70, 0x65, 0x24, 0x5a,
	0x99, 0xc9, 0xf7, 0x9d, 0xdc, 0x5a, 0x3e, 0x02, 0x2f, 0x4d, 0x04, 0x9b, 0xb0, 0x69, 0x3f, 0xf3,
	0xd2, 0x84, 0xdf, 0x42, 0xf0, 0x5a, 0xaa, 0x8f, 0x34, 0x11, 0xde, 0x84, 0x4d, 0x87, 0x59, 0x8b,
	0x1c, 0x3f, 0x57, 0x3b, 0xb3, 0x92, 0xc2, 0x27, 0x6d, 0x8b, 0x38, 0x87, 0xee, 0xa2, 0xd6, 0x52,
	0x74, 0x89, 0xa5, 0x9a, 0x87, 0xd0, 0x9b, 0x5b, 0x83, 0x56, 0x16, 0xb5, 0xf8, 0x47, 0xfc, 0x11,
	0xbb, 0x3e, 0x0b, 0x34, 0x85, 0xb4, 0x22, 0x68, 0xfa, 0x34, 0x88, 0x3c, 0xd4, 0x31, 0x4d, 0xc4,
	0xff, 0xd6, 0xd3, 0xe2, 0x30, 0x80, 0xae, 0x5d, 0x6f, 0x64, 0x18, 0x43, 0xef, 0x4d, 0xad, 0x28,
	0x10, 0xbf, 0x01, 0xbf, 0xac, 0x0a, 0x1a, 0xdc, 0xcb, 0x5c, 0x49, 0x0c, 0x5a, 0x1a, 0xdb, 0x31,
	0x68, 0x9d, 0x2f, 0x41, 0x8b, 0xd1, 0x23, 0x5c, 0x1d, 0x42, 0xeb, 0xb2, 0xe6, 0x03, 0x60, 0xfb,
	0x36, 0x31, 0xdb, 0x3b, 0x9b, 0x34, 0x86, 0x6c, 0xfd, 0xcc, 0x95, 0xd1, 0x17, 0x03, 0xc0, 0x3c,
	0xbf, 0xa4, 0x0d, 0x3d, 0x40, 0x8f, 0x12, 0x9f, 0xbb, 0x1e, 0x59, 0x5d, 0xda, 0x7a, 0x28, 0xf1,
	0x19, 0xeb, 0x79, 0xfa, 0x64, 0xe0, 0xbf, 0xe4, 0x39, 0x8f, 0x21, 0x68, 0x2e, 0x1d, 0x1f, 0xc7,
	0x7a, 0x19, 0xff, 0x79, 0x75, 0xe1, 0xf5, 0x6f, 0x4a, 0x97, 0x75, 0xd4, 0xe1, 0xf7, 0xe0, 0x63,
	0x9e, 0xf3, 0x91, 0xfb, 0x73, 0xba, 0x7d, 0xe1, 0xe0, 0x88, 0x8f, 0x32, 0x59, 0xb5, 0xb2, 0xd3,
	0x29, 0x34, 0xb2, 0xc3, 0x8c, 0x51, 0x67, 0x19, 0xd0, 0x7b, 0x7f, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x9f, 0x66, 0x05, 0x25, 0x26, 0x04, 0x00, 0x00,
}
